language: java
jdk:
- oraclejdk8
script:
  mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/31d1a4f0c3a5963bbf74
    on_success: always
    on_failure: always
    on_start: never     # options: [always|never|change]
